import type { RngService } from "../../packages/sim/src/index.ts";
import { float01, pick } from "./shared.ts";

const FIRST_F = [
  "Ana",
  "Daria",
  "Mila",
  "Sera",
  "Irena",
  "Marta",
  "Kira",
  "Emel",
  "Mara",
  "Risa",
  "Nora",
  "Petra",
  "Mira",
  "Helena",
  "Selka",
  "Lena",
  "Vera",
  "Talia",
  "Neris",
  "Olena",
  "Katya",
  "Sonia",
  "Elara",
  "Yana",
  "Rina",
  "Dessa",
  "Ilsa",
  "Maren",
  "Tessa",
  "Calia",
  "Vespa",
  "Nila",
  "Orla",
  "Petya",
  "Rhea",
  "Tova",
  "Una",
  "Vira",
  "Zora",
  "Alina",
  "Brina",
  "Cora",
  "Dana",
  "Eira",
  "Faye",
  "Gita",
  "Hana",
  "Iskra",
  "Jana",
  "Klara",
  "Liora",
  "Milaia",
  "Nadya",
  "Odette",
  "Pavla",
  "Radka",
  "Saskia",
  "Tamara",
  "Uliana",
  "Vesna",
  "Willa",
  "Zlata",
  "Amara",
  "Belma",
  "Celina",
  "Dorina",
  "Edina",
  "Freya",
  "Greta",
  "Halina",
];

const FIRST_M = [
  "Tomas",
  "Leon",
  "Viktor",
  "Pavel",
  "Jonah",
  "Adrian",
  "Danek",
  "Corin",
  "Elian",
  "Ivan",
  "Dalen",
  "Leo",
  "Anton",
  "Oren",
  "Marek",
  "Stefan",
  "Radek",
  "Joren",
  "Kaspar",
  "Nils",
  "Oskar",
  "Petar",
  "Roman",
  "Tomasz",
  "Ulric",
  "Vasil",
  "Wynn",
  "Yuri",
  "Zarek",
  "Arlen",
  "Boris",
  "Caleb",
  "Dimit",
  "Elias",
  "Fedor",
  "Goran",
  "Haris",
  "Ivo",
  "Josef",
  "Karel",
  "Lukas",
  "Milan",
  "Nolan",
  "Oleg",
  "Patrik",
  "Quentin",
  "Radomir",
  "Stellan",
  "Teodor",
  "Vadim",
  "Wiktor",
  "Yaromir",
  "Zoltan",
  "Aleks",
  "Bogdan",
  "Cyril",
  "Dominik",
  "Emil",
  "Filip",
  "Gustav",
  "Henrik",
  "Igor",
];

const FIRST_X = [
  "Ari",
  "Ren",
  "Sol",
  "Kai",
  "Noe",
  "Sami",
  "Val",
  "Eden",
  "Lux",
  "Rowan",
  "Nyx",
  "Quinn",
];

/** Expanded pool; NPC001–030 surnames included but generateName can prefer avoiding them. */
const SURNAMES = [
  "Belen",
  "Caris",
  "Dalvik",
  "Esker",
  "Fenric",
  "Havel",
  "Iskra",
  "Jelen",
  "Korr",
  "Linden",
  "Nerath",
  "Ostrov",
  "Pavelin",
  "Quen",
  "Selvik",
  "Toran",
  "Ulven",
  "Varden",
  "Wex",
  "Yaros",
  "Zoric",
  "Aldric",
  "Branek",
  "Cosmin",
  "Daris",
  "Ellan",
  "Forn",
  "Grell",
  "Holt",
  "Iven",
  "Jast",
  "Kerrin",
  "Lorik",
  "Mistral",
  "Narev",
  "Olan",
  "Pravic",
  "Renn",
  "Savel",
  "Tarn",
  "Ulan",
  "Veylan",
  "Wren",
  "Yel",
  "Zane",
  "Ashen",
  "Borek",
  "Cavren",
  "Dorin",
  "Elvek",
  "Falin",
  "Gres",
  "Harn",
  "Ilvar",
  "Joric",
  "Keld",
  "Lurek",
  "Morven",
  "Nalin",
  "Orvek",
  "Presh",
  "Rovan",
  "Sarn",
  "Tevik",
  "Urik",
  "Volan",
  "Amberg",
  "Belovar",
  "Cresnik",
  "Dunholt",
  "Eldren",
  "Falkor",
  "Gavril",
  "Hershel",
  "Iordan",
  "Jankov",
  "Kolar",
  "Levic",
  "Markan",
  "Novak",
  "Orban",
  "Petrovic",
  "Radovic",
  "Stanek",
  "Tomic",
  "Urban",
  "Vukovic",
  "Weiss",
  "Zelen",
  "Andric",
  "Blazek",
  "Cerny",
  "Dvorak",
  "Ermin",
  "Fiala",
  "Gorski",
  "Horvat",
  "Ivanek",
  "Juric",
  "Kovac",
  "Lazic",
  "Maric",
  "Nikolic",
  "Obrov",
  "Pavlic",
  "Ristic",
  "Simic",
  "Tesic",
  "Vlahovic",
  "Zoricov",
  "Alaric",
  "Brenner",
  "Colvin",
  "Damaris",
  "Easton",
  "Fenway",
  "Gresham",
  "Hadley",
  "Ilford",
  "Jasper",
  "Kendrick",
  "Langford",
  "Merrow",
  "Northam",
  "Oakley",
  "Prescott",
  "Quiller",
  "Redmond",
  "Ashford",
  "Beckett",
  "Carver",
  "Dalton",
  "Ellison",
  "Fairwin",
  "Garland",
  "Hartwell",
  "Ingram",
  "Jensen",
  "Keating",
  "Lambert",
  "Merrick",
  "Nash",
  "Ormond",
  "Perrin",
  "Quade",
  "Rowley",
  "Sheffield",
  "Tanner",
  "Underwood",
  "Vance",
  "Whitaker",
  "Yates",
  "Zell",
  "Baranov",
  "Chernov",
  "Dragan",
  "Emery",
  "Frost",
  "Glennon",
  "Harlan",
  "Ivers",
  "Jarvik",
  "Kessler",
  "Lindstrom",
  "Moravec",
  "Nyland",
  "Orloff",
  "Palmas",
  "Roszak",
  "Sorokin",
  "Thorne",
  "Ullman",
  "Volkov",
  "Warrick",
  "Zimmerman",
  "Abernathy",
  "Calloway",
  "Drummond",
  "Everhart",
  "Fitzroy",
  "Gallagher",
  "Holloway",
  "Ibrahim",
  "Johansen",
  "Kingsley",
];

const CANON_SURNAMES = new Set([
  "Velic",
  "Soren",
  "Mirev",
  "Kalen",
  "Veyr",
  "Orsen",
  "Talin",
  "Drazen",
  "Sol",
  "Drin",
  "Eren",
  "Ravel",
  "Melen",
  "Varic",
  "Kest",
  "Dovik",
  "Rusk",
  "Vale",
  "Hal",
  "Mora",
  "Sarin",
  "Rel",
  "Orr",
  "Kovan",
  "Arven",
  "Voss",
  "Dres",
  "Sorr",
  "Marin",
  "Vask",
]);

export type Sex = "F" | "M" | "X";

export function pickSex(rng: RngService): Sex {
  const r = float01(rng);
  if (r < 0.48) return "F";
  if (r < 0.96) return "M";
  return "X";
}

export function generateName(
  rng: RngService,
  sex: Sex,
  used: Set<string>,
  opts?: {
    avoidCanonSurnames?: boolean;
    surnameCounts?: Map<string, number>;
    maxSurnameReuse?: number;
    /** When true, surname reuse limits are looser / ignored after retries. */
    historicalPool?: boolean;
  },
): string {
  const firstPool = sex === "F" ? FIRST_F : sex === "M" ? FIRST_M : FIRST_X;
  const maxReuse = opts?.maxSurnameReuse ?? (opts?.historicalPool ? 12 : 4);

  for (let attempt = 0; attempt < 2000; attempt++) {
    const first = pick(rng, firstPool);
    const last = pick(rng, SURNAMES);
    if (opts?.avoidCanonSurnames && CANON_SURNAMES.has(last) && attempt < 800) continue;
    const reuse = opts?.surnameCounts?.get(last) ?? 0;
    // Soften surname cap gradually rather than digit suffixes
    const softCap = attempt < 600 ? maxReuse : attempt < 1200 ? maxReuse + 4 : maxReuse + 20;
    if (opts?.surnameCounts && reuse >= softCap && attempt < 1800) continue;
    const name = `${first} ${last}`;
    if (/\d/.test(name)) continue;
    if (!used.has(name)) {
      used.add(name);
      if (opts?.surnameCounts) {
        opts.surnameCounts.set(last, reuse + 1);
      }
      return name;
    }
  }

  // Last resort: compound surname without digits (still human-readable)
  for (let attempt = 0; attempt < 500; attempt++) {
    const first = pick(rng, firstPool);
    const a = pick(rng, SURNAMES);
    const b = pick(rng, SURNAMES);
    if (a === b) continue;
    const name = `${first} ${a}-${b}`;
    if (!used.has(name) && !/\d/.test(name)) {
      used.add(name);
      return name;
    }
  }

  throw new Error("generateName: exhausted name space without using digit suffixes");
}

export function inferSexFromName(name: string): Sex {
  const first = name.split(" ")[0] ?? "";
  if ((FIRST_F as readonly string[]).includes(first)) return "F";
  if ((FIRST_M as readonly string[]).includes(first)) return "M";
  if ((FIRST_X as readonly string[]).includes(first)) return "X";
  if (/a$|ia$|ra$|na$|la$|ka$|sa$/i.test(first)) return "F";
  return "M";
}

export function surnamePoolSize(): number {
  return SURNAMES.length;
}
