import type { Ideology, Skills, Traits } from "./shared.ts";
import { ISSUE_IDS, round3 } from "./shared.ts";

/** Hand-tuned profiles for NPC001–NPC030 (authored top figures). */
export type AuthoredProfile = {
  ideology: Ideology;
  traits: Traits;
  skills: Skills;
  issue_salience: Record<string, number>;
  first_elected_year?: number;
  presidential_status?: string;
  background?: string;
};

function sal(
  overrides: Partial<Record<(typeof ISSUE_IDS)[number], number>>,
): Record<string, number> {
  const out: Record<string, number> = {};
  for (const id of ISSUE_IDS) out[id] = 0.4;
  for (const [k, v] of Object.entries(overrides)) out[k] = v!;
  for (const k of Object.keys(out)) out[k] = round3(out[k]!);
  return out;
}

export const NPC_AUTHORED: Record<string, AuthoredProfile> = {
  NPC001: {
    // Mara Velic — two-term CR Civic Moderate president
    ideology: {
      economic: -0.05,
      social: 0.35,
      authority: -0.2,
      green: 0.15,
      nationalism: -0.15,
      globalism: 0.4,
    },
    traits: {
      ambition: 0.72,
      integrity: 0.68,
      ego: 0.55,
      riskTolerance: 0.42,
      sociability: 0.62,
      pragmatism: 0.78,
      institutionalism: 0.82,
      partyLoyalty: 0.58,
      factionLoyalty: 0.62,
      retirementInclination: 0.55,
    },
    skills: {
      campaigning: 0.72,
      fundraising: 0.65,
      legislation: 0.55,
      administration: 0.78,
      media: 0.7,
      negotiation: 0.8,
    },
    issue_salience: sal({
      ISS_REFORM: 0.78,
      ISS_CONCORD: 0.72,
      ISS_VASKARA: 0.65,
      ISS_EXEC: 0.6,
      ISS_HOUSING: 0.55,
    }),
    first_elected_year: 2006,
    presidential_status: "term_limited_incumbent",
    background: "law",
  },
  NPC002: {
    // Daria Soren — Speaker, LAB SD
    ideology: {
      economic: 0.4,
      social: 0.3,
      authority: -0.05,
      green: 0.2,
      nationalism: -0.1,
      globalism: 0.15,
    },
    traits: {
      ambition: 0.65,
      integrity: 0.7,
      ego: 0.48,
      riskTolerance: 0.4,
      sociability: 0.55,
      pragmatism: 0.75,
      institutionalism: 0.8,
      partyLoyalty: 0.62,
      factionLoyalty: 0.55,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.5,
      fundraising: 0.45,
      legislation: 0.78,
      administration: 0.55,
      media: 0.52,
      negotiation: 0.82,
    },
    issue_salience: sal({ ISS_LABOR: 0.7, ISS_WELFARE: 0.72, ISS_REFORM: 0.55, ISS_HOUSING: 0.5 }),
    first_elected_year: 2002,
    background: "law",
  },
  NPC003: {
    // Ana Mirev — Darsen governor, LAB frontrunner
    ideology: {
      economic: 0.45,
      social: 0.35,
      authority: -0.1,
      green: 0.25,
      nationalism: -0.1,
      globalism: 0.2,
    },
    traits: {
      ambition: 0.78,
      integrity: 0.65,
      ego: 0.52,
      riskTolerance: 0.55,
      sociability: 0.7,
      pragmatism: 0.68,
      institutionalism: 0.6,
      partyLoyalty: 0.7,
      factionLoyalty: 0.58,
      retirementInclination: 0.25,
    },
    skills: {
      campaigning: 0.78,
      fundraising: 0.62,
      legislation: 0.55,
      administration: 0.72,
      media: 0.7,
      negotiation: 0.68,
    },
    issue_salience: sal({
      ISS_LABOR: 0.75,
      ISS_HOUSING: 0.65,
      ISS_WELFARE: 0.7,
      ISS_CLIMATE: 0.45,
    }),
    first_elected_year: 2008,
    presidential_status: "frontrunner",
    background: "local government",
  },
  NPC004: {
    // Tomas Kalen — NU leader
    ideology: {
      economic: -0.35,
      social: -0.2,
      authority: 0.25,
      green: -0.15,
      nationalism: 0.3,
      globalism: -0.1,
    },
    traits: {
      ambition: 0.75,
      integrity: 0.55,
      ego: 0.62,
      riskTolerance: 0.5,
      sociability: 0.58,
      pragmatism: 0.6,
      institutionalism: 0.55,
      partyLoyalty: 0.72,
      factionLoyalty: 0.65,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.72,
      fundraising: 0.7,
      legislation: 0.58,
      administration: 0.55,
      media: 0.68,
      negotiation: 0.6,
    },
    issue_salience: sal({
      ISS_POLICING: 0.72,
      ISS_IMMIGRATION: 0.68,
      ISS_DEFENSE: 0.6,
      ISS_TRADE: 0.5,
    }),
    first_elected_year: 2004,
    presidential_status: "likely",
    background: "business",
  },
  NPC005: {
    // Leon Veyr — FM, CR frontrunner
    ideology: {
      economic: -0.05,
      social: 0.45,
      authority: -0.25,
      green: 0.2,
      nationalism: -0.25,
      globalism: 0.55,
    },
    traits: {
      ambition: 0.8,
      integrity: 0.62,
      ego: 0.58,
      riskTolerance: 0.55,
      sociability: 0.72,
      pragmatism: 0.7,
      institutionalism: 0.65,
      partyLoyalty: 0.6,
      factionLoyalty: 0.68,
      retirementInclination: 0.22,
    },
    skills: {
      campaigning: 0.7,
      fundraising: 0.6,
      legislation: 0.5,
      administration: 0.68,
      media: 0.75,
      negotiation: 0.82,
    },
    issue_salience: sal({
      ISS_CONCORD: 0.8,
      ISS_VASKARA: 0.75,
      ISS_TRADE: 0.65,
      ISS_DEFENSE: 0.55,
      ISS_REFORM: 0.55,
    }),
    first_elected_year: 2010,
    presidential_status: "frontrunner",
    background: "civil service",
  },
  NPC006: {
    ideology: {
      economic: 0.35,
      social: 0.55,
      authority: -0.25,
      green: 0.78,
      nationalism: -0.3,
      globalism: 0.4,
    },
    traits: {
      ambition: 0.7,
      integrity: 0.72,
      ego: 0.45,
      riskTolerance: 0.5,
      sociability: 0.65,
      pragmatism: 0.55,
      institutionalism: 0.5,
      partyLoyalty: 0.75,
      factionLoyalty: 0.7,
      retirementInclination: 0.28,
    },
    skills: {
      campaigning: 0.68,
      fundraising: 0.55,
      legislation: 0.6,
      administration: 0.5,
      media: 0.72,
      negotiation: 0.58,
    },
    issue_salience: sal({
      ISS_CLIMATE: 0.9,
      ISS_HOUSING: 0.65,
      ISS_LIBERTY: 0.6,
      ISS_REFORM: 0.55,
    }),
    first_elected_year: 2012,
    presidential_status: "likely",
    background: "nonprofit/advocacy",
  },
  NPC007: {
    ideology: {
      economic: 0.1,
      social: 0.05,
      authority: -0.05,
      green: 0.15,
      nationalism: 0.2,
      globalism: -0.3,
    },
    traits: {
      ambition: 0.62,
      integrity: 0.6,
      ego: 0.45,
      riskTolerance: 0.48,
      sociability: 0.6,
      pragmatism: 0.65,
      institutionalism: 0.45,
      partyLoyalty: 0.7,
      factionLoyalty: 0.72,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.6,
      fundraising: 0.5,
      legislation: 0.55,
      administration: 0.55,
      media: 0.52,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_DECENT: 0.85, ISS_TRADE: 0.55, ISS_CLIMATE: 0.4 }),
    first_elected_year: 2009,
    presidential_status: "possible",
    background: "agriculture",
  },
  NPC008: {
    ideology: {
      economic: 0.25,
      social: -0.25,
      authority: 0.4,
      green: -0.2,
      nationalism: 0.6,
      globalism: -0.5,
    },
    traits: {
      ambition: 0.75,
      integrity: 0.45,
      ego: 0.7,
      riskTolerance: 0.65,
      sociability: 0.55,
      pragmatism: 0.5,
      institutionalism: 0.35,
      partyLoyalty: 0.68,
      factionLoyalty: 0.6,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.75,
      fundraising: 0.55,
      legislation: 0.45,
      administration: 0.45,
      media: 0.78,
      negotiation: 0.5,
    },
    issue_salience: sal({
      ISS_TRADE: 0.75,
      ISS_IMMIGRATION: 0.7,
      ISS_VASKARA: 0.55,
      ISS_LABOR: 0.55,
    }),
    first_elected_year: 2014,
    presidential_status: "likely",
    background: "journalism/media",
  },
  NPC009: {
    ideology: {
      economic: -0.15,
      social: 0.35,
      authority: -0.15,
      green: 0.15,
      nationalism: -0.15,
      globalism: 0.4,
    },
    traits: {
      ambition: 0.6,
      integrity: 0.7,
      ego: 0.4,
      riskTolerance: 0.35,
      sociability: 0.5,
      pragmatism: 0.78,
      institutionalism: 0.7,
      partyLoyalty: 0.55,
      factionLoyalty: 0.6,
      retirementInclination: 0.4,
    },
    skills: {
      campaigning: 0.4,
      fundraising: 0.55,
      legislation: 0.55,
      administration: 0.82,
      media: 0.45,
      negotiation: 0.7,
    },
    issue_salience: sal({ ISS_TRADE: 0.65, ISS_REFORM: 0.6, ISS_OWNERSHIP: 0.55 }),
    first_elected_year: 2011,
    presidential_status: "possible",
    background: "civil service",
  },
  NPC010: {
    ideology: {
      economic: -0.1,
      social: 0.0,
      authority: 0.2,
      green: -0.05,
      nationalism: 0.15,
      globalism: 0.1,
    },
    traits: {
      ambition: 0.45,
      integrity: 0.75,
      ego: 0.35,
      riskTolerance: 0.4,
      sociability: 0.4,
      pragmatism: 0.7,
      institutionalism: 0.8,
      partyLoyalty: 0.15,
      factionLoyalty: 0.1,
      retirementInclination: 0.45,
    },
    skills: {
      campaigning: 0.3,
      fundraising: 0.25,
      legislation: 0.4,
      administration: 0.78,
      media: 0.35,
      negotiation: 0.6,
    },
    issue_salience: sal({ ISS_DEFENSE: 0.85, ISS_VASKARA: 0.75, ISS_CONCORD: 0.55 }),
    background: "military/veteran",
  },
  NPC011: {
    ideology: {
      economic: -0.05,
      social: 0.5,
      authority: -0.3,
      green: 0.2,
      nationalism: -0.2,
      globalism: 0.45,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.78,
      ego: 0.4,
      riskTolerance: 0.4,
      sociability: 0.55,
      pragmatism: 0.65,
      institutionalism: 0.75,
      partyLoyalty: 0.55,
      factionLoyalty: 0.65,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.45,
      fundraising: 0.4,
      legislation: 0.72,
      administration: 0.65,
      media: 0.5,
      negotiation: 0.7,
    },
    issue_salience: sal({ ISS_LIBERTY: 0.75, ISS_REFORM: 0.7, ISS_POLICING: 0.55 }),
    first_elected_year: 2013,
    presidential_status: "exploring",
    background: "law",
  },
  NPC012: {
    // Jonah Ravel — LAB leader / Workers' Left
    ideology: {
      economic: 0.65,
      social: 0.4,
      authority: -0.15,
      green: 0.3,
      nationalism: -0.2,
      globalism: 0.1,
    },
    traits: {
      ambition: 0.72,
      integrity: 0.68,
      ego: 0.55,
      riskTolerance: 0.6,
      sociability: 0.58,
      pragmatism: 0.5,
      institutionalism: 0.45,
      partyLoyalty: 0.65,
      factionLoyalty: 0.8,
      retirementInclination: 0.25,
    },
    skills: {
      campaigning: 0.65,
      fundraising: 0.5,
      legislation: 0.7,
      administration: 0.5,
      media: 0.62,
      negotiation: 0.55,
    },
    issue_salience: sal({ ISS_OWNERSHIP: 0.75, ISS_LABOR: 0.8, ISS_WELFARE: 0.7 }),
    first_elected_year: 2007,
    presidential_status: "possible",
    background: "unions",
  },
  NPC013: {
    ideology: {
      economic: 0.5,
      social: 0.15,
      authority: 0.05,
      green: 0.1,
      nationalism: 0.05,
      globalism: -0.05,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.65,
      ego: 0.4,
      riskTolerance: 0.4,
      sociability: 0.55,
      pragmatism: 0.7,
      institutionalism: 0.55,
      partyLoyalty: 0.75,
      factionLoyalty: 0.78,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.45,
      legislation: 0.65,
      administration: 0.5,
      media: 0.45,
      negotiation: 0.6,
    },
    issue_salience: sal({ ISS_LABOR: 0.85, ISS_WELFARE: 0.7 }),
    first_elected_year: 2005,
    background: "unions",
  },
  NPC014: {
    ideology: {
      economic: 0.25,
      social: 0.45,
      authority: -0.25,
      green: 0.35,
      nationalism: -0.25,
      globalism: 0.4,
    },
    traits: {
      ambition: 0.6,
      integrity: 0.6,
      ego: 0.45,
      riskTolerance: 0.55,
      sociability: 0.65,
      pragmatism: 0.65,
      institutionalism: 0.5,
      partyLoyalty: 0.55,
      factionLoyalty: 0.7,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.6,
      fundraising: 0.55,
      legislation: 0.6,
      administration: 0.5,
      media: 0.65,
      negotiation: 0.55,
    },
    issue_salience: sal({ ISS_HOUSING: 0.8, ISS_REFORM: 0.65, ISS_CLIMATE: 0.55 }),
    first_elected_year: 2015,
    background: "academia",
  },
  NPC015: {
    ideology: {
      economic: -0.45,
      social: 0.15,
      authority: 0.1,
      green: -0.1,
      nationalism: 0.1,
      globalism: 0.25,
    },
    traits: {
      ambition: 0.65,
      integrity: 0.55,
      ego: 0.55,
      riskTolerance: 0.55,
      sociability: 0.55,
      pragmatism: 0.7,
      institutionalism: 0.55,
      partyLoyalty: 0.6,
      factionLoyalty: 0.75,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.58,
      fundraising: 0.75,
      legislation: 0.6,
      administration: 0.55,
      media: 0.55,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_TRADE: 0.7, ISS_OWNERSHIP: 0.65, ISS_REFORM: 0.5 }),
    first_elected_year: 2008,
    presidential_status: "possible",
    background: "business",
  },
  NPC016: {
    ideology: {
      economic: -0.2,
      social: -0.1,
      authority: 0.15,
      green: -0.05,
      nationalism: 0.2,
      globalism: 0.0,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.65,
      ego: 0.4,
      riskTolerance: 0.4,
      sociability: 0.6,
      pragmatism: 0.72,
      institutionalism: 0.6,
      partyLoyalty: 0.7,
      factionLoyalty: 0.72,
      retirementInclination: 0.4,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.55,
      legislation: 0.6,
      administration: 0.55,
      media: 0.5,
      negotiation: 0.7,
    },
    issue_salience: sal({ ISS_WELFARE: 0.55, ISS_POLICING: 0.55, ISS_DECENT: 0.45 }),
    first_elected_year: 2006,
    presidential_status: "exploring",
    background: "local government",
  },
  NPC017: {
    ideology: {
      economic: -0.25,
      social: -0.4,
      authority: 0.4,
      green: -0.25,
      nationalism: 0.5,
      globalism: -0.35,
    },
    traits: {
      ambition: 0.7,
      integrity: 0.5,
      ego: 0.65,
      riskTolerance: 0.6,
      sociability: 0.5,
      pragmatism: 0.45,
      institutionalism: 0.4,
      partyLoyalty: 0.65,
      factionLoyalty: 0.8,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.7,
      fundraising: 0.55,
      legislation: 0.5,
      administration: 0.45,
      media: 0.68,
      negotiation: 0.45,
    },
    issue_salience: sal({ ISS_IMMIGRATION: 0.8, ISS_POLICING: 0.75, ISS_DEFENSE: 0.65 }),
    first_elected_year: 2011,
    background: "law",
  },
  NPC018: {
    // Risa Vale — CR party leader
    ideology: {
      economic: -0.05,
      social: 0.55,
      authority: -0.3,
      green: 0.25,
      nationalism: -0.25,
      globalism: 0.5,
    },
    traits: {
      ambition: 0.72,
      integrity: 0.65,
      ego: 0.5,
      riskTolerance: 0.55,
      sociability: 0.7,
      pragmatism: 0.65,
      institutionalism: 0.6,
      partyLoyalty: 0.7,
      factionLoyalty: 0.75,
      retirementInclination: 0.28,
    },
    skills: {
      campaigning: 0.7,
      fundraising: 0.65,
      legislation: 0.65,
      administration: 0.55,
      media: 0.7,
      negotiation: 0.68,
    },
    issue_salience: sal({ ISS_REFORM: 0.8, ISS_LIBERTY: 0.7, ISS_HOUSING: 0.55 }),
    first_elected_year: 2010,
    presidential_status: "possible",
    background: "law",
  },
  NPC019: {
    ideology: {
      economic: 0.0,
      social: 0.35,
      authority: -0.15,
      green: 0.15,
      nationalism: -0.1,
      globalism: 0.35,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.65,
      ego: 0.4,
      riskTolerance: 0.4,
      sociability: 0.6,
      pragmatism: 0.78,
      institutionalism: 0.65,
      partyLoyalty: 0.6,
      factionLoyalty: 0.7,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.5,
      fundraising: 0.5,
      legislation: 0.7,
      administration: 0.6,
      media: 0.5,
      negotiation: 0.75,
    },
    issue_salience: sal({ ISS_REFORM: 0.65, ISS_EXEC: 0.55, ISS_HOUSING: 0.5 }),
    first_elected_year: 2009,
    presidential_status: "possible",
    background: "civil service",
  },
  NPC020: {
    // Elian Mora — Chief Justice
    ideology: {
      economic: 0.0,
      social: 0.15,
      authority: -0.1,
      green: 0.05,
      nationalism: -0.05,
      globalism: 0.15,
    },
    traits: {
      ambition: 0.4,
      integrity: 0.88,
      ego: 0.35,
      riskTolerance: 0.25,
      sociability: 0.4,
      pragmatism: 0.7,
      institutionalism: 0.92,
      partyLoyalty: 0.05,
      factionLoyalty: 0.05,
      retirementInclination: 0.5,
    },
    skills: {
      campaigning: 0.15,
      fundraising: 0.1,
      legislation: 0.75,
      administration: 0.7,
      media: 0.3,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_LIBERTY: 0.7, ISS_REFORM: 0.65, ISS_EXEC: 0.6 }),
    background: "law",
  },
  NPC021: {
    ideology: {
      economic: 0.45,
      social: 0.2,
      authority: 0.0,
      green: 0.15,
      nationalism: 0.0,
      globalism: 0.05,
    },
    traits: {
      ambition: 0.65,
      integrity: 0.6,
      ego: 0.5,
      riskTolerance: 0.5,
      sociability: 0.65,
      pragmatism: 0.65,
      institutionalism: 0.55,
      partyLoyalty: 0.7,
      factionLoyalty: 0.7,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.65,
      fundraising: 0.55,
      legislation: 0.5,
      administration: 0.75,
      media: 0.55,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_LABOR: 0.75, ISS_HOUSING: 0.6, ISS_WELFARE: 0.65 }),
    first_elected_year: 2012,
    presidential_status: "possible",
    background: "unions",
  },
  NPC022: {
    ideology: {
      economic: -0.3,
      social: -0.15,
      authority: 0.2,
      green: -0.1,
      nationalism: 0.25,
      globalism: -0.05,
    },
    traits: {
      ambition: 0.6,
      integrity: 0.58,
      ego: 0.5,
      riskTolerance: 0.45,
      sociability: 0.55,
      pragmatism: 0.7,
      institutionalism: 0.55,
      partyLoyalty: 0.72,
      factionLoyalty: 0.65,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.6,
      fundraising: 0.6,
      legislation: 0.45,
      administration: 0.72,
      media: 0.5,
      negotiation: 0.6,
    },
    issue_salience: sal({ ISS_TRADE: 0.55, ISS_DECENT: 0.55, ISS_POLICING: 0.55 }),
    first_elected_year: 2007,
    presidential_status: "likely",
    background: "agriculture",
  },
  NPC023: {
    ideology: {
      economic: 0.0,
      social: 0.3,
      authority: -0.1,
      green: 0.15,
      nationalism: -0.1,
      globalism: 0.3,
    },
    traits: {
      ambition: 0.58,
      integrity: 0.62,
      ego: 0.45,
      riskTolerance: 0.45,
      sociability: 0.6,
      pragmatism: 0.72,
      institutionalism: 0.6,
      partyLoyalty: 0.6,
      factionLoyalty: 0.6,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.55,
      legislation: 0.5,
      administration: 0.7,
      media: 0.55,
      negotiation: 0.68,
    },
    issue_salience: sal({ ISS_HOUSING: 0.6, ISS_REFORM: 0.55, ISS_TRADE: 0.5 }),
    first_elected_year: 2010,
    presidential_status: "likely",
    background: "local government",
  },
  NPC024: {
    ideology: {
      economic: 0.15,
      social: 0.1,
      authority: -0.05,
      green: 0.2,
      nationalism: 0.15,
      globalism: -0.2,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.65,
      ego: 0.4,
      riskTolerance: 0.45,
      sociability: 0.6,
      pragmatism: 0.65,
      institutionalism: 0.5,
      partyLoyalty: 0.7,
      factionLoyalty: 0.7,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.45,
      legislation: 0.5,
      administration: 0.7,
      media: 0.5,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_DECENT: 0.8, ISS_TRADE: 0.5 }),
    first_elected_year: 2011,
    presidential_status: "possible",
    background: "agriculture",
  },
  NPC025: {
    ideology: {
      economic: -0.35,
      social: 0.1,
      authority: 0.1,
      green: -0.05,
      nationalism: 0.15,
      globalism: 0.2,
    },
    traits: {
      ambition: 0.6,
      integrity: 0.55,
      ego: 0.5,
      riskTolerance: 0.5,
      sociability: 0.55,
      pragmatism: 0.7,
      institutionalism: 0.55,
      partyLoyalty: 0.65,
      factionLoyalty: 0.7,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.65,
      legislation: 0.5,
      administration: 0.7,
      media: 0.5,
      negotiation: 0.6,
    },
    issue_salience: sal({ ISS_TRADE: 0.6, ISS_REFORM: 0.5 }),
    first_elected_year: 2009,
    presidential_status: "exploring",
    background: "business",
  },
  NPC026: {
    ideology: {
      economic: 0.3,
      social: 0.5,
      authority: -0.25,
      green: 0.75,
      nationalism: -0.25,
      globalism: 0.35,
    },
    traits: {
      ambition: 0.6,
      integrity: 0.7,
      ego: 0.4,
      riskTolerance: 0.5,
      sociability: 0.65,
      pragmatism: 0.55,
      institutionalism: 0.5,
      partyLoyalty: 0.7,
      factionLoyalty: 0.75,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.6,
      fundraising: 0.5,
      legislation: 0.55,
      administration: 0.7,
      media: 0.6,
      negotiation: 0.6,
    },
    issue_salience: sal({ ISS_CLIMATE: 0.85, ISS_HOUSING: 0.6, ISS_LIBERTY: 0.55 }),
    first_elected_year: 2013,
    presidential_status: "exploring",
    background: "nonprofit/advocacy",
  },
  NPC027: {
    ideology: {
      economic: 0.3,
      social: -0.15,
      authority: 0.3,
      green: -0.1,
      nationalism: 0.45,
      globalism: -0.4,
    },
    traits: {
      ambition: 0.65,
      integrity: 0.5,
      ego: 0.55,
      riskTolerance: 0.6,
      sociability: 0.55,
      pragmatism: 0.55,
      institutionalism: 0.4,
      partyLoyalty: 0.7,
      factionLoyalty: 0.65,
      retirementInclination: 0.3,
    },
    skills: {
      campaigning: 0.7,
      fundraising: 0.5,
      legislation: 0.45,
      administration: 0.65,
      media: 0.65,
      negotiation: 0.55,
    },
    issue_salience: sal({ ISS_TRADE: 0.7, ISS_LABOR: 0.6, ISS_IMMIGRATION: 0.55 }),
    first_elected_year: 2014,
    presidential_status: "likely",
    background: "local government",
  },
  NPC028: {
    ideology: {
      economic: -0.1,
      social: 0.4,
      authority: -0.2,
      green: 0.2,
      nationalism: -0.15,
      globalism: 0.45,
    },
    traits: {
      ambition: 0.58,
      integrity: 0.65,
      ego: 0.45,
      riskTolerance: 0.45,
      sociability: 0.65,
      pragmatism: 0.7,
      institutionalism: 0.6,
      partyLoyalty: 0.6,
      factionLoyalty: 0.65,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.55,
      fundraising: 0.6,
      legislation: 0.5,
      administration: 0.72,
      media: 0.55,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_TRADE: 0.65, ISS_DEFENSE: 0.5, ISS_REFORM: 0.55 }),
    first_elected_year: 2011,
    presidential_status: "possible",
    background: "business",
  },
  NPC029: {
    ideology: {
      economic: 0.1,
      social: 0.1,
      authority: 0.0,
      green: 0.15,
      nationalism: 0.2,
      globalism: -0.25,
    },
    traits: {
      ambition: 0.55,
      integrity: 0.65,
      ego: 0.4,
      riskTolerance: 0.45,
      sociability: 0.65,
      pragmatism: 0.65,
      institutionalism: 0.5,
      partyLoyalty: 0.75,
      factionLoyalty: 0.75,
      retirementInclination: 0.35,
    },
    skills: {
      campaigning: 0.6,
      fundraising: 0.45,
      legislation: 0.5,
      administration: 0.7,
      media: 0.55,
      negotiation: 0.65,
    },
    issue_salience: sal({ ISS_DECENT: 0.85, ISS_TRADE: 0.55 }),
    first_elected_year: 2012,
    presidential_status: "possible",
    background: "local government",
  },
  NPC030: {
    ideology: {
      economic: 0.4,
      social: 0.25,
      authority: -0.05,
      green: 0.2,
      nationalism: -0.1,
      globalism: 0.15,
    },
    traits: {
      ambition: 0.5,
      integrity: 0.7,
      ego: 0.4,
      riskTolerance: 0.4,
      sociability: 0.55,
      pragmatism: 0.7,
      institutionalism: 0.65,
      partyLoyalty: 0.7,
      factionLoyalty: 0.6,
      retirementInclination: 0.4,
    },
    skills: {
      campaigning: 0.45,
      fundraising: 0.4,
      legislation: 0.75,
      administration: 0.55,
      media: 0.45,
      negotiation: 0.7,
    },
    issue_salience: sal({ ISS_LABOR: 0.8, ISS_WELFARE: 0.75 }),
    first_elected_year: 2003,
    background: "unions",
  },
};
